### PR TITLE
Remove Dockerfile templating in main build 

### PR DESCRIPTION
**Pull request by JulianCBC**
Build args can be used to specify the version of containers in `FROM` lines, so skip a step in the build process by passing the Terraform version in as an argument instead of templating the Dockerfile.

I haven't done the same conversion to the EKS image as it doesn't build at present.

This conflicts with #27 so I'll sort that out once one of these is merged.

### CODE REVIEW

**Comment by ozbillwang** [comment]
Thanks for your PR. let's hold this change, until we plan to put OpenTofu (need be GA release) in it.

**Comment by JulianCBC** [comment]
I don't understand, this isn't changing the tags, this is just some cleanup.

**Comment by ozbillwang** [comment]
TODO list:

* add opentofu binary in this image
* define new tags
* No `latest` tag any more. 
* rollback the new tags we merged last time (`1`, `1.8`) 

New tags for discussion

* `alpine/terragrunt:tf1.8.3`
*  `alpine/terragrunt:otf1.7.1`

**Comment by JulianCBC** [comment]
> * `alpine/terragrunt:otf1.7.1` or `alpine/terragrunt:ot1.7.1`

"tf" is TerraForm, i.e. letter per syllable, so "otf" being OpenToFu also makes sense.

**Comment by JulianCBC** [comment]
I've rebased this over the latest changes in `master`. Let's handle that TODO list in separate merge requests.

**Comment by ozbillwang** [comment]
> TODO list:
> 
> * add opentofu binary in this image
> * define new tags
> * No `latest` tag any more.
> * rollback the new tags we merged last time (`1`, `1.8`)
> 
> New tags for discussion
> 
> * `alpine/terragrunt:tf1.8.3`
> * `alpine/terragrunt:otf1.7.1` or `alpine/terragrunt:ot1.7.1`

opentofu has been installed in the latest image now.

```
docker run -ti --rm alpine/terragrunt tofu --version
OpenTofu v1.7.1
on linux_amd64
```

For the tagging for both terraform and tofu, will add the feature later

**Pull request merged**
